### ISSUE TITLE
Added the ability to pass stylesheet by string

### ISSUE THREAD

**Issue by karlisup** [edenspiekermann/iframify#14]
Hi @HugoGiraudel,

Please, correct me if I'm wrong. It's possible to load stylesheet into the iframe only by passing a selector. In this case it would mean that styles that are loaded into iframe are present outside the iframe as well.
Wouldn't it be a nice thing to pass stylesheet down the iframe the same way as you pass the script (as a string)?

For example:

``` javascript
// getOptions - overwrite if stylesheet passed as a string
opts.stylesheets = getStylingNodes(opts.stylesSelector || 'link[rel*=stylesheet], style');
opts.stylesheets = (opts.metaStylesheets ? opts.metaStylesheets : opts.stylesheets);

// the call
return iframify(this, {
  'metaStylesheets': ' <link rel="stylesheet" type="text/css" href="assets/css/style.css"> '
})
```

**Comment by KittyGiraudel** [comment]
Hey Karlis,

That’s very true. I think I should revisit the API a little to make it more flexible. Basically, having a `extraHead` and `extraBody`, where the content is literally printed at the bottom of `<head>` and `<body>` respectively.

What do you think?

**Comment by karlisup** [comment]
It sounds like a nice solution to me. Like you already said - it gives more flexibility.
Thanks!

**Comment by KittyGiraudel** [comment]
Alright, done. 

`styles` option no longer exists. It is now named `headExtra` and allows injecting arbitrary content at the end of `<head>`.
`scripts` option no longer exists. It is now named `bodyExtra` and allows injecting arbitrary content at the end of `<body>`.
