### ISSUE TITLE
How do you use your module?

### ISSUE THREAD

**Issue by dylannirvana** [edenspiekermann/iframify#15]
`npm install edenspiekermann/iframify `  and then trying to use gets you a `require not a function` error,
`var iframify = require('iframify');` in gulp,

```
var component = document.querySelector('.page-layout');
var iframe = iframify(component, {
  headExtra: '<style>.component { color: red; }</style>'
});
```
gets you a not so nice `window is not defined` error that breaks the application.

Can you clarify why your module does not work with node's require() function? Or otherwise how to use this module?
Thanks....

**Comment by KittyGiraudel** [comment]
Good morning,

`iframify` is a client-side library. It manipulates the DOM. It needs a DOM element. It outputs a DOM element. You cannot run it on Node. I’m not even sure why you would try to run it on Node.
