### ISSUE TITLE
Import @font-face declarations

### ISSUE THREAD

**Issue by KittyGiraudel** [edenspiekermann/iframify#3]
I am not entirely sure what would be the best solution here. Importing all the fonts without checking if they are being used by the element (and its children) might be huge, especially if some of them are base 64 encoded. But checking which fonts a component need might be even harder… I am not even sure it’s possible.

**Comment by zachleat** [comment]
Visual accuracy is probably more important than weight (you can play around with optimizing later, imo).

To get the active font-family on an element is a bit tricky. For `fontfamily.io` I used a technique that set the font-family and then compared the dimensions of the element (with a static and diverse innerHTML). But you might have to do this for each element 😢

**Comment by KittyGiraudel** [comment]
> Visual accuracy is probably more important than weight (you can play around with optimizing later, imo).

The problem is not really weight per se, especially given that this script is likely to run in a document where performance does not matter so much (please no one quotes me out of context on this 😀).

The problem is execution time. On my very first version of the script, instead of grabbing all the styles from the component, I grabbed all the styles from the page. All the stylesheets and style tags if you will. Then, I copied everything inside the iframe. When running the script on a page with about 20 components, my browser crashed.

I am afraid that if we copy all the font-face declarations (which can be numerous, we know that), it can get slow to execute. Especially if they are encoded inside the stylesheets. But I get that’s the safest bet right now.

**Comment by KittyGiraudel** [comment]
Done with #8.
