### ISSUE TITLE
Doesn't support attributes on html or body elements

### ISSUE THREAD

**Issue by Fotiman** [edenspiekermann/iframify#9]
getIframeContentForNode generates the html and body elements with no attributes.  It might be helpful to include add any existing attributes from the global html and body elements to the generated ones.

**Comment by KittyGiraudel** [comment]
Very good idea.

**Comment by Fotiman** [comment]
And/or allowing them to be explicitly defined via some configuration.

**Comment by KittyGiraudel** [comment]
Done with: https://github.com/edenspiekermann/iframify/commit/0957408b2c21aa6c6b51088df4c6a58a1b24d231.
